[project]
name = "cafe-managment-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fpdf2>=2.8.3",
    "pytz>=2025.2",
    "reportlab>=4.4.3",
    "streamlit>=1.47.1",
]
